"""g02 persistent orchestrator

Revision ID: 0001_g02
Revises:
Create Date: 2026-08-16 11:13:59.246305
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_g02"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "generation_snapshots",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("draft_id", sa.String(length=26), nullable=False),
        sa.Column("intent_revision_id", sa.String(length=26), nullable=False),
        sa.Column("outline_revision_id", sa.String(length=26), nullable=False),
        sa.Column("template_version_id", sa.String(length=26), nullable=False),
        sa.Column("mode_id", sa.String(length=32), nullable=False),
        sa.Column("source_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("engine_version", sa.String(length=80), nullable=False),
        sa.Column("container_version", sa.String(length=160), nullable=False),
        sa.Column("font_pack_version", sa.String(length=80), nullable=False),
        sa.Column("provider_config_version", sa.String(length=80), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_generation_snapshots_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_snapshots")),
        sa.UniqueConstraint(
            "id", "organization_id", name="uq_generation_snapshots_id_organization"
        ),
        sa.UniqueConstraint(
            "organization_id", "snapshot_sha256", name="uq_generation_snapshots_org_sha"
        ),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("aggregate_type", sa.String(length=40), nullable=False),
        sa.Column("aggregate_id", sa.String(length=26), nullable=False),
        sa.Column("dedupe_key", sa.String(length=360), nullable=False),
        sa.Column("destination", sa.String(length=320), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('event', 'task')", name=op.f("ck_outbox_events_valid_kind")),
        sa.CheckConstraint(
            "status IN ('pending', 'dispatched')", name=op.f("ck_outbox_events_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_outbox_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_outbox_events_dedupe_key")),
    )
    op.create_index(
        "ix_outbox_events_pending",
        "outbox_events",
        ["status", "available_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "service_actors",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_service_actors_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_actors")),
        sa.UniqueConstraint("id", "organization_id", name="uq_service_actors_id_organization"),
    )
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("snapshot_id", sa.String(length=26), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("latest_seq", sa.BigInteger(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("progress_completed", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_token", sa.String(length=26), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("test_behavior", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage IN ('deck_planning', 'slide_generation', 'deck_qa', 'compiling', 'package_qa', 'publishing')",
            name=op.f("ck_generation_jobs_valid_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'cancel_requested', 'cancelled', 'succeeded', 'partially_succeeded', 'failed')",
            name=op.f("ck_generation_jobs_valid_status"),
        ),
        sa.CheckConstraint("attempt >= 0", name=op.f("ck_generation_jobs_attempt_nonnegative")),
        sa.CheckConstraint(
            "latest_seq >= 0", name=op.f("ck_generation_jobs_latest_seq_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_generation_jobs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "organization_id"],
            ["generation_snapshots.id", "generation_snapshots.organization_id"],
            name="fk_generation_jobs_snapshot_org",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_jobs")),
        sa.UniqueConstraint("id", "organization_id", name="uq_generation_jobs_id_organization"),
    )
    op.create_index(
        "ix_generation_jobs_org_created",
        "generation_jobs",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=False),
        sa.Column("route", sa.String(length=320), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resource_id", sa.String(length=26), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id", "organization_id"],
            ["service_actors.id", "service_actors.organization_id"],
            name="fk_idempotency_records_actor_org",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "organization_id",
            "actor_id",
            "route",
            "idempotency_key",
            name="uq_idempotency_records_scope",
        ),
    )
    op.create_index(
        "ix_idempotency_records_expires", "idempotency_records", ["expires_at"], unique=False
    )
    op.create_table(
        "generation_job_slides",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("job_id", sa.String(length=26), nullable=False),
        sa.Column("slide_id", sa.String(length=26), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("failure_mode", sa.String(length=24), nullable=False),
        sa.Column("logical_task_key", sa.String(length=320), nullable=False),
        sa.Column("artifact_ref", sa.String(length=320), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage IN ('content_generation', 'rendering', 'qa')",
            name=op.f("ck_generation_job_slides_valid_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'ready', 'failed', 'retrying', 'cancelled')",
            name=op.f("ck_generation_job_slides_valid_status"),
        ),
        sa.CheckConstraint(
            "attempt >= 0", name=op.f("ck_generation_job_slides_attempt_nonnegative")
        ),
        sa.CheckConstraint(
            "max_attempts BETWEEN 1 AND 5",
            name=op.f("ck_generation_job_slides_max_attempts_bounded"),
        ),
        sa.CheckConstraint(
            "position >= 1", name=op.f("ck_generation_job_slides_position_positive")
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "organization_id"],
            ["generation_jobs.id", "generation_jobs.organization_id"],
            name="fk_generation_job_slides_job_org",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_job_slides")),
        sa.UniqueConstraint("job_id", "position", name="uq_generation_job_slides_position"),
        sa.UniqueConstraint("job_id", "slide_id", name="uq_generation_job_slides_slide"),
        sa.UniqueConstraint(
            "logical_task_key", name=op.f("uq_generation_job_slides_logical_task_key")
        ),
    )
    op.create_table(
        "job_events",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("job_id", sa.String(length=26), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("snapshot_id", sa.String(length=26), nullable=False),
        sa.Column("slide_id", sa.String(length=26), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("progress_completed", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trace_id", sa.String(length=160), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "organization_id"],
            ["generation_jobs.id", "generation_jobs.organization_id"],
            name="fk_job_events_job_org",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
        sa.UniqueConstraint("job_id", "seq", name="uq_job_events_job_seq"),
    )
    op.create_index(
        "ix_job_events_job_occurred", "job_events", ["job_id", "occurred_at"], unique=False
    )
    op.create_table(
        "published_fixture_manifests",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("job_id", sa.String(length=26), nullable=False),
        sa.Column("logical_task_key", sa.String(length=320), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "organization_id"],
            ["generation_jobs.id", "generation_jobs.organization_id"],
            name="fk_published_fixture_manifests_job_org",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_published_fixture_manifests")),
        sa.UniqueConstraint("job_id", name="uq_published_fixture_manifests_job"),
        sa.UniqueConstraint("logical_task_key", name="uq_published_fixture_manifests_task"),
    )
    op.create_table(
        "usage_reservations",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("job_id", sa.String(length=26), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reserved_units", sa.Integer(), nullable=False),
        sa.Column("settled_units", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('reserved', 'settled', 'released')",
            name=op.f("ck_usage_reservations_valid_status"),
        ),
        sa.CheckConstraint(
            "reserved_units >= 0", name=op.f("ck_usage_reservations_reserved_units_nonnegative")
        ),
        sa.CheckConstraint(
            "settled_units >= 0", name=op.f("ck_usage_reservations_settled_units_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "organization_id"],
            ["generation_jobs.id", "generation_jobs.organization_id"],
            name="fk_usage_reservations_job_org",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_reservations")),
        sa.UniqueConstraint("job_id", name="uq_usage_reservations_job"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usage_reservations")
    op.drop_table("published_fixture_manifests")
    op.drop_index("ix_job_events_job_occurred", table_name="job_events")
    op.drop_table("job_events")
    op.drop_table("generation_job_slides")
    op.drop_index("ix_idempotency_records_expires", table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index("ix_generation_jobs_org_created", table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_table("service_actors")
    op.drop_index("ix_outbox_events_pending", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("generation_snapshots")
    op.drop_table("organizations")
    # ### end Alembic commands ###
