"""G03 identity tenancy artifacts

Revision ID: 5d3890b5cbb8
Revises: 0001_g02
Create Date: 2026-08-16 11:54:32.387229
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5d3890b5cbb8'
down_revision: str | Sequence[str] | None = '0001_g02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('issuer', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=320), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_normalized', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f('ck_users_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('issuer', 'subject', name='uq_users_issuer_subject')
    )
    op.create_index('ix_users_email_normalized', 'users', ['email_normalized'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('organization_id', sa.String(length=26), nullable=False),
    sa.Column('artifact_type', sa.String(length=80), nullable=False),
    sa.Column('partition', sa.String(length=16), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("partition IN ('quarantine', 'clean', 'tmp', 'published')", name=op.f('ck_artifacts_valid_partition')),
    sa.CheckConstraint("status IN ('pending', 'published', 'revoked', 'deleted')", name=op.f('ck_artifacts_valid_status')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_artifacts_size_nonnegative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_artifacts_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('id', 'organization_id', name='uq_artifacts_id_organization'),
    sa.UniqueConstraint('object_key', name='uq_artifacts_object_key')
    )
    op.create_index('ix_artifacts_org_created', 'artifacts', ['organization_id', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('organization_id', sa.String(length=26), nullable=False),
    sa.Column('actor_id', sa.String(length=26), nullable=False),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=26), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('request_id', sa.String(length=160), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_request', 'audit_logs', ['request_id'], unique=False)
    op.create_table('entitlements',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('organization_id', sa.String(length=26), nullable=False),
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('max_slides_per_deck', sa.Integer(), nullable=False),
    sa.Column('monthly_slide_limit', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('allowed_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_concurrent_jobs >= 1', name=op.f('ck_entitlements_concurrency_positive')),
    sa.CheckConstraint('max_slides_per_deck BETWEEN 1 AND 100', name=op.f('ck_entitlements_slides_bounded')),
    sa.CheckConstraint('monthly_slide_limit >= 0', name=op.f('ck_entitlements_monthly_slides_nonnegative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_entitlements_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlements')),
    sa.UniqueConstraint('organization_id', name='uq_entitlements_organization')
    )
    op.create_table('memberships',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('organization_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name=op.f('ck_memberships_valid_role')),
    sa.CheckConstraint("status IN ('active', 'revoked')", name=op.f('ck_memberships_valid_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_memberships_organization_user')
    )
    op.create_index('ix_memberships_user_status', 'memberships', ['user_id', 'status'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('organization_id', sa.String(length=26), nullable=False),
    sa.Column('job_id', sa.String(length=26), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=320), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_usage_ledger_quantity_nonnegative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_usage_ledger_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_ledger')),
    sa.UniqueConstraint('organization_id', 'dedupe_key', name='uq_usage_ledger_org_dedupe')
    )
    op.create_index('ix_usage_ledger_org_occurred', 'usage_ledger', ['organization_id', 'occurred_at'], unique=False)
    op.create_table('artifact_download_grants',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('organization_id', sa.String(length=26), nullable=False),
    sa.Column('artifact_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('request_id', sa.String(length=160), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id', 'organization_id'], ['artifacts.id', 'artifacts.organization_id'], name='fk_artifact_download_grants_artifact_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_artifact_download_grants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_download_grants'))
    )
    op.create_index('ix_artifact_download_grants_expires', 'artifact_download_grants', ['expires_at'], unique=False)
    op.add_column(
        'idempotency_records',
        sa.Column('actor_kind', sa.String(length=16), server_default='service', nullable=True),
    )
    op.drop_constraint(op.f('fk_idempotency_records_actor_org'), 'idempotency_records', type_='foreignkey')
    op.add_column('organizations', sa.Column('slug', sa.String(length=160), nullable=True))
    op.add_column('organizations', sa.Column('personal_owner_user_id', sa.String(length=26), nullable=True))
    op.add_column(
        'organizations', sa.Column('lock_version', sa.Integer(), server_default='1', nullable=False)
    )
    op.add_column('organizations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE organizations SET slug = 'legacy-' || lower(id) WHERE slug IS NULL")
    op.execute(
        "UPDATE idempotency_records SET actor_kind = 'service' WHERE actor_kind IS NULL"
    )
    op.alter_column('organizations', 'slug', nullable=False)
    op.alter_column('idempotency_records', 'actor_kind', nullable=False, server_default=None)
    op.alter_column('organizations', 'lock_version', server_default=None)
    op.create_unique_constraint('uq_organizations_personal_owner_user', 'organizations', ['personal_owner_user_id'])
    op.create_unique_constraint('uq_organizations_slug', 'organizations', ['slug'])
    op.create_foreign_key(op.f('fk_organizations_personal_owner_user_id_users'), 'organizations', 'users', ['personal_owner_user_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint(op.f('ck_organizations_valid_kind'), 'organizations', "kind IN ('synthetic', 'personal', 'team')")
    op.execute(
        """
        INSERT INTO users (
            id, issuer, subject, email, email_normalized, display_name, status,
            last_login_at, created_at, updated_at
        )
        SELECT
            '01ARZ3NDEKTSV4RRFFQ69G5FAC', 'urn:instant-ppt:local', 'local-default',
            'local-default@local.invalid', 'local-default@local.invalid',
            'Local default user', 'active', now(), now(), now()
        WHERE EXISTS (
            SELECT 1 FROM organizations WHERE id = '01ARZ3NDEKTSV4RRFFQ69G5FAA'
        )
        ON CONFLICT (issuer, subject) DO NOTHING
        """
    )
    op.execute(
        """
        UPDATE organizations
        SET kind = 'personal',
            name = 'Local default user 的工作区',
            slug = 'personal-01arz3ndektsv4rrffq69g5fac',
            personal_owner_user_id = '01ARZ3NDEKTSV4RRFFQ69G5FAC',
            lock_version = lock_version + 1,
            updated_at = now()
        WHERE id = '01ARZ3NDEKTSV4RRFFQ69G5FAA'
          AND EXISTS (
              SELECT 1 FROM users WHERE id = '01ARZ3NDEKTSV4RRFFQ69G5FAC'
          )
        """
    )
    op.execute(
        """
        INSERT INTO memberships (
            id, organization_id, user_id, role, status, created_at, updated_at
        )
        SELECT
            '01ARZ3NDEKTSV4RRFFQ69G5FAD', '01ARZ3NDEKTSV4RRFFQ69G5FAA',
            '01ARZ3NDEKTSV4RRFFQ69G5FAC', 'owner', 'active', now(), now()
        WHERE EXISTS (
            SELECT 1 FROM organizations WHERE id = '01ARZ3NDEKTSV4RRFFQ69G5FAA'
        )
        ON CONFLICT (organization_id, user_id) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO entitlements (
            id, organization_id, plan_code, max_slides_per_deck,
            monthly_slide_limit, max_concurrent_jobs, allowed_modes,
            effective_from, effective_until, created_at, updated_at
        )
        SELECT
            '01ARZ3NDEKTSV4RRFFQ69G5FAE', '01ARZ3NDEKTSV4RRFFQ69G5FAA',
            'p1-default', 30, 300, 1, '["native"]'::jsonb,
            now(), NULL, now(), now()
        WHERE EXISTS (
            SELECT 1 FROM organizations WHERE id = '01ARZ3NDEKTSV4RRFFQ69G5FAA'
        )
        ON CONFLICT (organization_id) DO NOTHING
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM idempotency_records WHERE actor_kind = 'user'")
    op.execute(
        """
        UPDATE organizations
        SET kind = 'synthetic',
            name = 'G02 synthetic organization',
            personal_owner_user_id = NULL,
            updated_at = now()
        WHERE id = '01ARZ3NDEKTSV4RRFFQ69G5FAA'
        """
    )
    op.drop_constraint(op.f('ck_organizations_valid_kind'), 'organizations', type_='check')
    op.drop_constraint(op.f('fk_organizations_personal_owner_user_id_users'), 'organizations', type_='foreignkey')
    op.drop_constraint('uq_organizations_slug', 'organizations', type_='unique')
    op.drop_constraint('uq_organizations_personal_owner_user', 'organizations', type_='unique')
    op.drop_column('organizations', 'deleted_at')
    op.drop_column('organizations', 'lock_version')
    op.drop_column('organizations', 'personal_owner_user_id')
    op.drop_column('organizations', 'slug')
    op.create_foreign_key(op.f('fk_idempotency_records_actor_org'), 'idempotency_records', 'service_actors', ['actor_id', 'organization_id'], ['id', 'organization_id'], ondelete='CASCADE')
    op.drop_column('idempotency_records', 'actor_kind')
    op.drop_index('ix_artifact_download_grants_expires', table_name='artifact_download_grants')
    op.drop_table('artifact_download_grants')
    op.drop_index('ix_usage_ledger_org_occurred', table_name='usage_ledger')
    op.drop_table('usage_ledger')
    op.drop_index('ix_memberships_user_status', table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('entitlements')
    op.drop_index('ix_audit_logs_request', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_artifacts_org_created', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_users_email_normalized', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
