"""g05 draft workspace revisions templates

Revision ID: 925b69af0f8f
Revises: 9e9a61eff690
Create Date: 2026-08-16 13:47:14.264710
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "925b69af0f8f"
down_revision: str | Sequence[str] | None = "9e9a61eff690"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templates",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
        sa.UniqueConstraint("slug", name="uq_templates_slug"),
    )
    op.create_index(
        "ix_templates_catalog", "templates", ["is_active", "category", "sort_order"], unique=False
    )
    op.create_table(
        "template_versions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("template_id", sa.String(length=26), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("theme_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("page_roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("editable_elements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine_compatibility", sa.String(length=120), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_template_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_template_versions_template_id_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_versions")),
        sa.UniqueConstraint("content_sha256", name=op.f("uq_template_versions_content_sha256")),
        sa.UniqueConstraint("id", "template_id", name="uq_template_versions_id_template"),
        sa.UniqueConstraint("template_id", "version", name="uq_template_versions_template_version"),
    )
    op.create_table(
        "drafts",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("owner_user_id", sa.String(length=26), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("topic", sa.String(length=1000), nullable=False),
        sa.Column("source_id", sa.String(length=26), nullable=True),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("template_version_id", sa.String(length=26), nullable=False),
        sa.Column("current_intent_revision_id", sa.String(length=26), nullable=True),
        sa.Column("current_outline_revision_id", sa.String(length=26), nullable=True),
        sa.Column("approved_outline_revision_id", sa.String(length=26), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("mode = 'native'", name=op.f("ck_drafts_native_mode_only")),
        sa.CheckConstraint(
            "status IN ('draft', 'outline_ready', 'approved', 'deleted')",
            name=op.f("ck_drafts_valid_status"),
        ),
        sa.CheckConstraint("lock_version >= 1", name=op.f("ck_drafts_lock_version_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_drafts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_drafts_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "organization_id"],
            ["sources.id", "sources.organization_id"],
            name="fk_drafts_source_org",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"],
            ["template_versions.id"],
            name=op.f("fk_drafts_template_version_id_template_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drafts")),
        sa.UniqueConstraint("id", "organization_id", name="uq_drafts_id_organization"),
    )
    op.create_index(
        "ix_drafts_org_updated", "drafts", ["organization_id", "updated_at"], unique=False
    )
    op.create_table(
        "provider_calls",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("draft_id", sa.String(length=26), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("purpose", sa.String(length=80), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("repair_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed', 'rate_limited', 'timed_out')",
            name=op.f("ck_provider_calls_valid_status"),
        ),
        sa.CheckConstraint(
            "input_tokens >= 0", name=op.f("ck_provider_calls_input_tokens_nonnegative")
        ),
        sa.CheckConstraint(
            "output_tokens >= 0", name=op.f("ck_provider_calls_output_tokens_nonnegative")
        ),
        sa.CheckConstraint(
            "repair_count BETWEEN 0 AND 2", name=op.f("ck_provider_calls_repair_count_bounded")
        ),
        sa.ForeignKeyConstraint(
            ["draft_id", "organization_id"],
            ["drafts.id", "drafts.organization_id"],
            name="fk_provider_calls_draft_org",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_calls")),
    )
    op.create_index(
        "ix_provider_calls_org_started",
        "provider_calls",
        ["organization_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "intent_revisions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("draft_id", sa.String(length=26), nullable=False),
        sa.Column("based_on_revision_id", sa.String(length=26), nullable=True),
        sa.Column("actor_id", sa.String(length=26), nullable=False),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("provider_call_id", sa.String(length=26), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_kind IN ('user', 'ai', 'system')", name=op.f("ck_intent_revisions_valid_actor")
        ),
        sa.ForeignKeyConstraint(
            ["draft_id", "organization_id"],
            ["drafts.id", "drafts.organization_id"],
            name="fk_intent_revisions_draft_org",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_call_id"],
            ["provider_calls.id"],
            name=op.f("fk_intent_revisions_provider_call_id_provider_calls"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intent_revisions")),
    )
    op.create_index(
        "ix_intent_revisions_draft_created",
        "intent_revisions",
        ["draft_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "outline_revisions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("draft_id", sa.String(length=26), nullable=False),
        sa.Column("based_on_revision_id", sa.String(length=26), nullable=True),
        sa.Column("actor_id", sa.String(length=26), nullable=False),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("provider_call_id", sa.String(length=26), nullable=True),
        sa.Column("operation", sa.String(length=40), nullable=False),
        sa.Column("story_summary", sa.Text(), nullable=False),
        sa.Column("target_slide_count", sa.Integer(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_kind IN ('user', 'ai', 'system')", name=op.f("ck_outline_revisions_valid_actor")
        ),
        sa.CheckConstraint(
            "target_slide_count BETWEEN 4 AND 30",
            name=op.f("ck_outline_revisions_target_slide_count_bounded"),
        ),
        sa.ForeignKeyConstraint(
            ["draft_id", "organization_id"],
            ["drafts.id", "drafts.organization_id"],
            name="fk_outline_revisions_draft_org",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_call_id"],
            ["provider_calls.id"],
            name=op.f("fk_outline_revisions_provider_call_id_provider_calls"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outline_revisions")),
        sa.UniqueConstraint("id", "organization_id", name="uq_outline_revisions_id_organization"),
    )
    op.create_index(
        "ix_outline_revisions_draft_created",
        "outline_revisions",
        ["draft_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "outline_approvals",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("draft_id", sa.String(length=26), nullable=False),
        sa.Column("outline_revision_id", sa.String(length=26), nullable=False),
        sa.Column("intent_revision_id", sa.String(length=26), nullable=False),
        sa.Column("template_version_id", sa.String(length=26), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("source_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_input_hash", sa.String(length=64), nullable=False),
        sa.Column("approved_by", sa.String(length=26), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["draft_id", "organization_id"],
            ["drafts.id", "drafts.organization_id"],
            name="fk_outline_approvals_draft_org",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["outline_revision_id", "organization_id"],
            ["outline_revisions.id", "outline_revisions.organization_id"],
            name="fk_outline_approvals_revision_org",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outline_approvals")),
        sa.UniqueConstraint("outline_revision_id", name="uq_outline_approvals_outline_revision"),
    )
    op.create_table(
        "outline_slides",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("outline_revision_id", sa.String(length=26), nullable=False),
        sa.Column("outline_slide_id", sa.String(length=26), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("slide_type", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("key_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 1", name=op.f("ck_outline_slides_position_positive")),
        sa.ForeignKeyConstraint(
            ["outline_revision_id", "organization_id"],
            ["outline_revisions.id", "outline_revisions.organization_id"],
            name="fk_outline_slides_revision_org",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outline_slides")),
        sa.UniqueConstraint(
            "outline_revision_id", "outline_slide_id", name="uq_outline_slides_revision_slide"
        ),
        sa.UniqueConstraint(
            "outline_revision_id", "position", name="uq_outline_slides_revision_position"
        ),
    )
    template_table = sa.table(
        "templates",
        sa.column("id", sa.String()),
        sa.column("slug", sa.String()),
        sa.column("name", sa.String()),
        sa.column("category", sa.String()),
        sa.column("description", sa.String()),
        sa.column("is_builtin", sa.Boolean()),
        sa.column("is_active", sa.Boolean()),
        sa.column("sort_order", sa.Integer()),
    )
    version_table = sa.table(
        "template_versions",
        sa.column("id", sa.String()),
        sa.column("template_id", sa.String()),
        sa.column("version", sa.Integer()),
        sa.column("mode", sa.String()),
        sa.column("theme_spec", postgresql.JSONB()),
        sa.column("page_roles", postgresql.JSONB()),
        sa.column("editable_elements", postgresql.JSONB()),
        sa.column("engine_compatibility", sa.String()),
        sa.column("content_sha256", sa.String()),
    )
    templates = [
        (
            "01ARZ3NDEKTSV4RRFFQ69G5FB4",
            "editorial-cobalt",
            "编辑部蓝",
            "business",
            "克制的钴蓝编辑网格，适合汇报与策略材料。",
            10,
            "#1746D1",
            "#F7F3E8",
            "78aea6a1fdc6f086c97d28dfd1b17861f40455a4424a9683a70fa34f1e5ef9bf",
        ),
        (
            "01ARZ3NDEKTSV4RRFFQ69G5FB6",
            "signal-red",
            "信号红",
            "strategy",
            "高对比标题与数据标记，适合结论先行的策略提案。",
            20,
            "#B42318",
            "#FFF8F0",
            "a141324fef206467e3bee0079afbfc932429bef6977eedcf89925776e9343ba3",
        ),
        (
            "01ARZ3NDEKTSV4RRFFQ69G5FB8",
            "field-notes",
            "研究手记",
            "research",
            "温暖纸面与注释式层级，适合培训和研究叙事。",
            30,
            "#365314",
            "#FAF7ED",
            "912538855ed86030a80b4dd09396329add48379791f57acc1818726e88a367cc",
        ),
    ]
    op.bulk_insert(
        template_table,
        [
            {
                "id": item[0],
                "slug": item[1],
                "name": item[2],
                "category": item[3],
                "description": item[4],
                "is_builtin": True,
                "is_active": True,
                "sort_order": item[5],
            }
            for item in templates
        ],
    )
    version_ids = [
        "01ARZ3NDEKTSV4RRFFQ69G5FB5",
        "01ARZ3NDEKTSV4RRFFQ69G5FB7",
        "01ARZ3NDEKTSV4RRFFQ69G5FB9",
    ]
    op.bulk_insert(
        version_table,
        [
            {
                "id": version_ids[index],
                "template_id": item[0],
                "version": 1,
                "mode": "native",
                "theme_spec": {
                    "schemaVersion": 1,
                    "themeId": item[1],
                    "colorTokens": {"primary": item[6], "background": item[7]},
                    "fontFamilies": ["Noto Sans CJK SC"],
                    "aspectRatio": "16:9",
                },
                "page_roles": ["cover", "section", "content", "data", "closing"],
                "editable_elements": ["text", "shape", "chart", "table"],
                "engine_compatibility": "ppt-master-v4.7.0",
                "content_sha256": item[8],
            }
            for index, item in enumerate(templates)
        ],
    )
    op.execute(
        """
        CREATE FUNCTION instant_ppt_reject_immutable_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'immutable workspace record cannot be updated or deleted';
        END;
        $$
        """
    )
    for table_name in (
        "template_versions",
        "intent_revisions",
        "outline_revisions",
        "outline_slides",
        "outline_approvals",
    ):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table_name}_immutable
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION instant_ppt_reject_immutable_mutation()
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in (
        "template_versions",
        "intent_revisions",
        "outline_revisions",
        "outline_slides",
        "outline_approvals",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_immutable ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS instant_ppt_reject_immutable_mutation()")
    op.drop_table("outline_slides")
    op.drop_table("outline_approvals")
    op.drop_index("ix_outline_revisions_draft_created", table_name="outline_revisions")
    op.drop_table("outline_revisions")
    op.drop_index("ix_intent_revisions_draft_created", table_name="intent_revisions")
    op.drop_table("intent_revisions")
    op.drop_index("ix_provider_calls_org_started", table_name="provider_calls")
    op.drop_table("provider_calls")
    op.drop_index("ix_drafts_org_updated", table_name="drafts")
    op.drop_table("drafts")
    op.drop_table("template_versions")
    op.drop_index("ix_templates_catalog", table_name="templates")
    op.drop_table("templates")
    # ### end Alembic commands ###
