"""g04 sources upload sessions and artifacts

Revision ID: 9e9a61eff690
Revises: 5d3890b5cbb8
Create Date: 2026-08-16 12:42:06.301207
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9e9a61eff690"
down_revision: str | Sequence[str] | None = "5d3890b5cbb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("input_artifact_id", sa.String(length=26), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("extension", sa.String(length=12), nullable=False),
        sa.Column("declared_mime_type", sa.String(length=160), nullable=False),
        sa.Column("detected_mime_type", sa.String(length=160), nullable=True),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("scan_status", sa.String(length=16), nullable=False),
        sa.Column("parse_status", sa.String(length=16), nullable=False),
        sa.Column("scan_attempt", sa.Integer(), nullable=False),
        sa.Column("parse_attempt", sa.Integer(), nullable=False),
        sa.Column("scan_decision", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_package", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parser_version", sa.String(length=160), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_detail", sa.String(length=1000), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scan_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parse_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parse_status IN ('pending', 'running', 'succeeded', 'failed')",
            name=op.f("ck_sources_valid_parse_status"),
        ),
        sa.CheckConstraint(
            "scan_status IN ('pending', 'running', 'clean', 'rejected', 'failed')",
            name=op.f("ck_sources_valid_scan_status"),
        ),
        sa.CheckConstraint(
            "status IN ('upload_pending', 'uploading', 'uploaded', 'scanning', "
            "'clean', 'parsing', 'parsed', 'rejected', 'parse_failed', 'cancelled')",
            name=op.f("ck_sources_valid_status"),
        ),
        sa.CheckConstraint(
            "parse_attempt BETWEEN 0 AND 5", name=op.f("ck_sources_parse_attempt_bounded")
        ),
        sa.CheckConstraint(
            "scan_attempt BETWEEN 0 AND 5", name=op.f("ck_sources_scan_attempt_bounded")
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_sources_size_nonnegative")),
        sa.ForeignKeyConstraint(
            ["input_artifact_id", "organization_id"],
            ["artifacts.id", "artifacts.organization_id"],
            name="fk_sources_input_artifact_org",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sources_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("id", "organization_id", name="uq_sources_id_organization"),
    )
    op.create_index(
        "ix_sources_org_created", "sources", ["organization_id", "created_at"], unique=False
    )
    op.create_table(
        "source_artifacts",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("source_id", sa.String(length=26), nullable=False),
        sa.Column("artifact_id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("parser_version", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('markdown', 'asset', 'conversion_profile')",
            name=op.f("ck_source_artifacts_valid_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id", "organization_id"],
            ["artifacts.id", "artifacts.organization_id"],
            name="fk_source_artifacts_artifact_org",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "organization_id"],
            ["sources.id", "sources.organization_id"],
            name="fk_source_artifacts_source_org",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_artifacts")),
        sa.UniqueConstraint("artifact_id", name="uq_source_artifacts_artifact"),
    )
    op.create_index(
        "ix_source_artifacts_source_kind", "source_artifacts", ["source_id", "kind"], unique=False
    )
    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("organization_id", sa.String(length=26), nullable=False),
        sa.Column("source_id", sa.String(length=26), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("declared_mime_type", sa.String(length=160), nullable=False),
        sa.Column("expected_sha256", sa.String(length=64), nullable=False),
        sa.Column("expected_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("max_bytes", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_code", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'uploaded', 'completed', 'expired', 'rejected')",
            name=op.f("ck_upload_sessions_valid_status"),
        ),
        sa.CheckConstraint(
            "expected_size_bytes >= 1", name=op.f("ck_upload_sessions_expected_size_positive")
        ),
        sa.CheckConstraint(
            "max_bytes >= expected_size_bytes", name=op.f("ck_upload_sessions_max_covers_expected")
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "organization_id"],
            ["sources.id", "sources.organization_id"],
            name="fk_upload_sessions_source_org",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_sessions")),
        sa.UniqueConstraint("object_key", name="uq_upload_sessions_object_key"),
        sa.UniqueConstraint("source_id", name="uq_upload_sessions_source"),
    )
    op.create_index(
        "ix_upload_sessions_org_expires",
        "upload_sessions",
        ["organization_id", "expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_upload_sessions_org_expires", table_name="upload_sessions")
    op.drop_table("upload_sessions")
    op.drop_index("ix_source_artifacts_source_kind", table_name="source_artifacts")
    op.drop_table("source_artifacts")
    op.drop_index("ix_sources_org_created", table_name="sources")
    op.drop_table("sources")
    # ### end Alembic commands ###
